name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '45 23 * * 0'

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: Dockerfile

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: [lint]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Meta
        id: meta
        run: |
          echo "::set-output name=build_version::$(echo $(npm show lighthouse version))"
          echo "::set-output name=build_date::$(echo $(date -u "+%Y%m%dT%H%M%SZ"))"
          exit ${PIPESTATUS[0]}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            genv/lighthouse:${{ steps.meta.outputs.build_version }}
            genv/lighthouse:${{ steps.meta.outputs.build_version }}-${{ steps.meta.outputs.build_date }}
            genv/lighthouse:latest
