name: Build

on:
  schedule:
    - cron: '15 4 1 * *'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: [lint]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build Meta
        id: meta
        run: |
          echo "build_version=$(echo $(npm show lighthouse version))" >> $GITHUB_OUTPUT
          echo "build_date=$(echo $(date -u "+%Y%m%dT%H%M%SZ"))" >> $GITHUB_OUTPUT
          exit ${PIPESTATUS[0]}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            genv/lighthouse:${{ steps.meta.outputs.build_version }}
            genv/lighthouse:${{ steps.meta.outputs.build_version }}-${{ steps.meta.outputs.build_date }}
            genv/lighthouse:latest
